### ISSUE TITLE
Game is literally unplayable.

### ISSUE THREAD

**Issue by TheGuardian117** [deimors/FloatMyHouse#1]
On Very Low, and Low setting. The house takes off without regard to fuel, and doesn't stop. Eventually the world is so small that it disappears from view. Issue found with help of @willikev. @ottenbel

10/10 - Game of the year!

**Comment by deimors** [comment]
Hrmm, I'm pretty sure that behaviour is intended, we designed the game to penalize players who don't set the quality high enough.
